name: l10n-subs-pot-update
on:
  push:
    paths:
    - 'l10n/**/en_US.po'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 */12 * * *'

env:
  GIT_PUSH_BRANCH: l10n-crowdin
  GIT_USER: gimbalabs-ci
  GIT_EMAIL: integrations@gimbalabs.io
  BASE_LOCALE: en_US
  POT_FILES: l10n/youtube/subtitles/part1/subs.pot

jobs:
  update-subs-template:
    name: Update subtitle templates from English translation
    runs-on: ubuntu-latest
    steps:
    - name: 
      run: |
        set -x
        ls -hal
        for file in ${POT_FILES}
        do
          cp -a $(dirname ${file})/${BASE_LOCALE}.po ${file}
        done
    - name: push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: ${GIT_PUSH_BRANCH}
        rebase: 'true'
        commit-message: '[Auto] Update pot file(s)'
        files: 'l10n/**/*.pot'
        name: ${GIT_USER}
        email: ${GIT_EMAIL}
