name: l10n-ci-automerge
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge-l10n-ci:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.ref }} == 'l10n-ci' # check PR origin branch
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.12.0"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_METHOD: squash
